### ISSUE TITLE
Using variable for data-inline-src returns error

### ISSUE THREAD

**Issue by ethanfox** [vnphanquang/svelte-put#156]
I have an array of strings that has all of my icon names in it.  

Whenever trying to use: 
` <svg data-inline-src=${realIconList[3]} />
`

I get the error: cannot find svg source for ${realIconList[3]}

**Comment by vnphanquang** [comment]
Hello @ethanfox thanks for raising this. Someone else filed the same issue about the same time as you did, so i'm gonna mark this as duplicated. Please see my answer at https://github.com/vnphanquang/svelte-put/issues/155 😄

**Comment by vnphanquang** [comment]
closing this for now. Feel free to reopen if you need to, otherwise please continue at #155
