### ISSUE TITLE
Typescript Errors

### ISSUE THREAD

**Issue by jamess-ais** [vnphanquang/svelte-put#182]
Hi! I've been having a terrible issue with all of our open dialog functions. The types are constantly causing error squiggles despite working just fine. Below are screenshots showing the different errors

Function:
![image](https://user-images.githubusercontent.com/122755711/230200532-df97ef72-201d-4ec5-ac9d-5c975926272d.png)

Component TS error:
![image](https://user-images.githubusercontent.com/122755711/230200806-f8a817c5-60ea-45c6-b191-9af93700d1b5.png)

props TS error
![image](https://user-images.githubusercontent.com/122755711/230200963-ceb17c02-3632-4995-b989-c04c627d9d7b.png)

DeleteBorrowers Component:
![image](https://user-images.githubusercontent.com/122755711/230201164-6679abde-5f32-4815-aed4-3908a85dfac3.png)

I'm a smidge clueless as to why there's an issue here. It seems everything should be work and I'm 95% sure it used to all work until an update recently. Thanks for any assistance!

**Comment by vnphanquang** [comment]
Thanks for reporting, will take a look

**Comment by vnphanquang** [comment]
hello @jamess-ais I've looked in a couple repos where `@svelte-put/modal` is used but could not reproduce the reported type errors. My testing was done in latest version of all dependencies:

```json
{
    "@svelte-put/modal": "^1.0.0",
    "@sveltejs/kit": "^1.15.2",
    "svelte": "^3.58.0",
    "svelte-check": "^3.2.0",
    "typescript": "^5.0.4",
    "vite": "^4.2.1"
}
```

If the issue persists, please consider creating a minimal reproduction repo / stackblitz; it would be much appreciated. Thanks in advance.

**Comment by JamesSatherley** [comment]
Hi @vnphanquang 

We went to create a reproduction repository and it didn't reproduce. We then went to view the issue in our use case and the issue is no longer present. We're unsure what caused it initially or what fixed it but I'll message here if it pops up again in the future

Thanks!

**Comment by vnphanquang** [comment]
Thanks @JamesSatherley for taking the time. Sometimes either the svelte language server needs to be restarted or vscode itself does. I'll keep this issue open for some more time.

**Comment by vnphanquang** [comment]
closing as stale. Please feel free to reopen if you are still having the same problem. Thanks
