### ISSUE TITLE
movables do not behave as expected on mobile / with touch input

### ISSUE THREAD

**Issue by EmeraldSnorlax** [vnphanquang/svelte-put#242]
dragging elements with movable with touch input does not actually move them -- it instead scrolls the viewport (i.e. default behaviour with no movement)

https://developer.mozilla.org/en-US/docs/Web/API/Element/touchmove_event may be relevant

**Comment by vnphanquang** [comment]
@EmeraldSnorlax Thanks. I'm looking into it and will roll out support for touch devices in an upcoming release :pray:

**Comment by vnphanquang** [comment]
added support in [3.1.0](https://github.com/vnphanquang/svelte-put/releases/tag/%40svelte-put%2Fmovable%403.1.0). Closing for now, please feel free to reopen if you are still having problems.
