### ISSUE TITLE
XY was created with unknown prop 'topmost'

### ISSUE THREAD

**Issue by BCsabaEngine** [vnphanquang/svelte-put#292]
I get ```<ModalXY> was created with unknown prop 'topmost'``` console warning when creating/displaying a new modal. Is topmost is a valid property in this context?

```
<aside class="s-modal-portal {$$props.class ?? ''}">
  {#each $store as modal, index (modal.id)}
    <svelte:component
      this={modal.component}
      {...modal.props}
      topmost={index === $store.length - 1}
      on:resolve={(event) => onResolve(modal, event)}
    />
  {/each}
</aside>
```

**Comment by vnphanquang** [comment]
@BCsabaEngine The `topmost` prop is [used internally by the `Modal.svelte` component exported from `@svelte-put/modal`](https://github.com/vnphanquang/svelte-put/blob/9cedde8c33ecce7b1a4058425bf29b6f7a292b91/packages/modal/src/lib/Modal.svelte#L97). If you are writing your own custom modal component, it has no effect so you can safely ignore the warning. This is definitely one of the decision that I regret when looking back, and something to improve in the future.
