### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by bitboxer** [vnphanquang/svelte-put#299]
Sadly the license was deleted in commit [6c2f4dd93306705c9163c4db73b545fadf21add2](https://github.com/vnphanquang/svelte-put/commit/6c2f4dd93306705c9163c4db73b545fadf21add2). The Readme still has a badge linking to it saying it is MIT, but without the license file, this is not really clear if it is true or not.

**Comment by vnphanquang** [comment]
Oops, good catch. Thank you. I added an MIT `LICENSE` file at project root via https://github.com/vnphanquang/svelte-put/commit/3b082e60e3d7ce468e3a19678021b3403ee3b1aa, which is what I intended to do after the commit you mentioned. All packages should share the same license file (they should already have a license field in their package.json, I believe).

Closing for now. Let me know if there is still any concern.
