### ISSUE TITLE
[inline-svg@next] Type gen on Windows outputs incorrect path separator

### ISSUE THREAD

**Issue by xiBread** [vnphanquang/svelte-put#320]
The separator on Windows is `\` which is seen as an escape.

![image](https://github.com/user-attachments/assets/d667a7d5-7511-4ec3-bda5-1e6aa76189fe)

![image](https://github.com/user-attachments/assets/85b60bb4-0895-44dc-ac68-5906f50cab7b)

Caused by `path.relative` usage on [this line](https://github.com/vnphanquang/svelte-put/blob/59d505294502f65fb3dfef762a6303b7965562a3/packages/inline-svg/src/vite/internals.js#L39)

**Comment by vnphanquang** [comment]
Thanks for reporting. I'll look into this soon.

**Comment by vnphanquang** [comment]
@xiBread can you let me know what version of Svelte & `@svelte-put/inline-svg` you are running on? All latest I assume?

**Comment by xiBread** [comment]
@vnphanquang
- `svelte@5.0.0-next.182`
- `@svelte-put/inline-svg@4.0.0-next.2`

**Comment by vnphanquang** [comment]
Fixed via https://github.com/vnphanquang/svelte-put/commit/b7e69fe31946fe875454f764ec4a81f377ad7603, patch is now available in [@svelte-put/inline-svg@4.0.0-next.4](https://github.com/vnphanquang/svelte-put/releases/tag/%40svelte-put/inline-svg%404.0.0-next.4).

Thanks again for reporting, and sorry about the delay.
