### ISSUE TITLE
[movable] Exclude text nodes when click to drag

### ISSUE THREAD

**Issue by vnphanquang** [vnphanquang/svelte-put#33]
Right now if no `trigger` is provided,`click` event is registered anywhere inside the node. This makes it hard to copy texts. There should be an option to exclude text nodes from the action.

**Comment by vnphanquang** [comment]
Alternate solution was implemented in https://github.com/vnphanquang/svelte-put/commit/05828766f109109a990e00a4a52436c0f45e3992: an `ignore` option that receives css selectors. This scales better. And users should be encouraged to use the `trigger`

**Comment by Neptunium1129** [comment]
how to drag modal exclude text nodes?

**Comment by vnphanquang** [comment]
@Neptunium1129 Hey there you can take a look at the docs here: https://svelte-put.vnphanquang.com/docs/movable#ignore-children-nodes-from-triggering-movablemovable-on-click

In short you can specify `ignore` option with a css selector ([introduced in 1.2.0](https://github.com/vnphanquang/svelte-put/blob/main/packages/actions/movable/CHANGELOG.md#120)). I recommend, however, to use the `handle` option instead (previously `trigger`) and have a dedicate element to move your modal (if possible of course).

Let me know if you have any other question. Cheers!
