### ISSUE TITLE
shortcut: allow shortcuts to exclude modifiers

### ISSUE THREAD

**Issue by mrankine** [vnphanquang/svelte-put#330]
In the following configuration, hitting Ctrl + Enter causes _both_ callbacks to run. I would like to the second callback to run only when Ctrl is _not_ held.
```<svelte:window
    use:shortcut={{
        trigger: [
            { key: "Enter", modifier: "ctrl", callback: () => console.log("Ctrl + Enter") },
            { key: "Enter", callback: () => console.log("Enter") },
        ],
    }} />
```
I had expected `modifier: undefined` (or `modifier: []`) to mean "run only if no modifiers held".

Is there a sensible/idiomatic way of making the second callback run only when Enter is pressed without modifiers?

**Comment by vnphanquang** [comment]
@mrankine hey that's a fair expectation and an oversight from my side so sorry. I'll put up quick patch to allow such behavior. Not sure exactly what the `modifier` value will be in this case but I'm thinking any falsy value (`false`, `null`, `undefined`) means `expect no modifier`.

Patch should be up within 24 hours.

**Comment by mrankine** [comment]
That's great, thanks for the quick response and great library!

**Comment by mrankine** [comment]
A backport to the Svelte 4 version would be very helpful, if possible. 🙏

**Comment by vnphanquang** [comment]
Available now in [4.0.1](https://github.com/vnphanquang/svelte-put/releases/tag/%40svelte-put/shortcut%404.0.1) and [3.1.2](https://github.com/vnphanquang/svelte-put/releases/tag/%40svelte-put/shortcut%403.1.2).

Docs: https://svelte-put.vnphanquang.com/docs/shortcut#no-modifier
Svelte V4 Docs: https://svelte-put-svelte-4.vnphanquang.com/docs/shortcut#modifier

Closing for now, but please let me know if you still have any problem. Thanks again for reporting.

**Comment by vnphanquang** [comment]
@mrankine just a quick note, the patch above introduced some semver breaking changes so I had to adjust a little bit. Please set your `trigger.modifier` to `null` or `false` explicitly in your use case.

You may also find setting `type` to `keyup` might help avoiding your particular problem.

Let me know if there is still any issue.

**Comment by mrankine** [comment]
Thanks for the headsup
