### ISSUE TITLE
@svelte-put/shortcut@3.1.2 breaks key configurations

### ISSUE THREAD

**Issue by peterkogo** [vnphanquang/svelte-put#334]
I had to fix our dependency of the shortcut library to the version 3.1.1 over at [Svelte Flow](https://github.com/xyflow/xyflow/pull/4897) because it breaks all of our key configurations.

I was able to pinpoint it to the fact that before we'd just pass an empty array as the modifier.

```js
use:shortcut={{
  trigger: {
     key: "Backspace",
     modifier: [],
     callback: ...
  },
  type: 'keyup'
}}
```

This is fixable with passing `undefined` instead.

We also had a number of key bindings directly to modifier keys which just don't work anymore at all.
```js
use:shortcut={{
  trigger: {
     key: "Meta",
     modifier: undefined,
     callback: ...
  },
  type: 'keydown'
}}
```

I was not able to fix this with the new version.

I would also like to point out that 3.1.2 breaks semver rules and is not a minor version.

P.S. Thanks for the great library, has been a breeze so far to work with!

**Comment by vnphanquang** [comment]
@peterkogo hi thanks for reporting. That was unfortunate. I had a feeling this would happen after the patch was released to support #330 but was too ignorant to see it through. My apologies.

And yes you are right, this release was not up to semver specs.

Will add your examples to the test cases and fix this soon.

**Comment by vnphanquang** [comment]
@peterkogo [3.2.0](https://github.com/vnphanquang/svelte-put/releases/tag/%40svelte-put%2Fshortcut%403.2.0) should fix it. I've marked `3.1.2` as deprecated now.

Closing for now but feel free to let me know if there is still any issue.

Thanks again for reporting. I appreciate it, really.

**Comment by peterkogo** [comment]
@vnphanquang Thank you for your swift response! Everything is working again on my side.
